language: rust
os:
  - linux
  - osx
env:
  global:
    - LD_LIBRARY_PATH: /usr/local/lib
    - secure: sUAJLHh4K5wb2Q6edJuiDzgHZybUljRX1CnWA4RJ69HPIiCZa00X2xWz+2RKBagXT+IMQuJb/wpuvgwDv0xeoKDMbSXUBhh+046ct1JiucJKorRZbJYT6N4kUgFUkSilH2Qe62YRGxSefKKebuHn08trBs4cLWv0F8A894JRgpI=
before_install:
  - wget https://github.com/google/cayley/releases/download/v0.4.0/cayley_0.4.0_linux_amd64.tar.gz
  - tar -xvzf cayley_0.4.0_linux_amd64.tar.gz
before_script:
  - ./cayley_0.4.0_linux_amd64/cayley http --dbpath=./cayley_0.4.0_linux_amd64/30kmoviedata.nq.gz &
  - rustc -v
  - cargo -V
script:
  - cargo build -v
  - cargo test -v
  - cargo doc
after_script:
  - cd target && curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
