language: rust
os:
  - linux
  - osx
env:
  global:
    - LD_LIBRARY_PATH: /usr/local/lib
    - secure: XRR3hMjyXw5Yoh+wuef9FtePjtytF0lpajPgfs9kILQH6F920SJDAM555SBmZFjXxTBxoqNEwY1c74zNqaVyOTKuVc/YgD0sFBi3240ETGMySI4rOJiT9D2nN6M6VUcQ3RyUmTJdwFn9ZIrhz7f2MEwxKSsqA/3o/c0in/vhNIA=
before_install:
  - wget https://github.com/google/cayley/releases/download/v0.4.0/cayley_0.4.0_linux_amd64.tar.gz
  - tar -xvzf cayley_0.4.0_linux_amd64.tar.gz
before_script:
  - ./cayley_0.4.0_linux_amd64/cayley http --dbpath=./cayley_0.4.0_linux_amd64/30kmoviedata.nq.gz &
  - rustc -v
  - cargo -V
script:
  - cargo build -v
  - cargo test -v
  - cargo doc
after_script:
  - ln -s ./target/doc ./doc
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
