language: rust
env:
  global:
    - secure: oFqpv/0T9yVxT89o0iUZ+FZ4BGEzrixSsdM3HcpMfXClqfnXU5RynuHaWJCkM2OlYWX2iLmQWiLsSfUTdea1fYUWrWbxXU/CUg04VqHXOHbDdm9WH+wEF2mgEdahJ6A3RYkTROy7fNHZ5xxCy3ycwuABdd173UhhaBmo2uxnv/E=
before_install:
  - wget https://github.com/google/cayley/releases/download/v0.4.0/cayley_0.4.0_linux_amd64.tar.gz
  - tar -xvzf cayley_0.4.0_linux_amd64.tar.gz
before_script:
  - ./cayley_0.4.0_linux_amd64/cayley http --dbpath=./cayley_0.4.0_linux_amd64/30kmoviedata.nq.gz &
after_script:
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
