[package]
name = "cayley"
version = "0.0.1"
authors = ["Ulric Wilfred <shaman.sir@gmail.com>"]

[lib]
name = "cayley"
doc = true

[dependencies.hyper]
git = "https://github.com/hyperium/hyper"
doc = false
